{"name": "test_learn", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\api_test\\\\test_learn.yaml'", "trace": "self = <testcase.learn.test_learn.TestLearn object at 0x0000020E9C14B1F0>\n\n    @allure.story(\"测试用例\")\n    def test_learn(self):\n>       self.get_case_step(selector='get_case')\n\ntestcase\\learn\\test_learn.py:18: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nkw\\casekw\\casekw.py:13: in get_case_step\n    name = self.get_data(selector)\nutils\\yamlutil.py:39: in get_data\n    data = self.read_yaml(FilePath)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <testcase.learn.test_learn.TestLearn object at 0x0000020E9C14B1F0>\npath = 'C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\api_test\\\\test_learn.yaml'\n\n    def read_yaml(self, path):\n        \"\"\"\n        读取yaml文件数据\n        :return:\n        \"\"\"\n>       with open(path, encoding='utf-8') as fp:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\api_test\\\\test_learn.yaml'\n\nutils\\yamlutil.py:18: FileNotFoundError"}, "steps": [{"name": "获取开课中课程信息", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\Administrator\\\\PycharmProjects\\\\api_test\\\\test_learn.yaml'\n", "trace": "  File \"C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\api_test\\kw\\casekw\\casekw.py\", line 13, in get_case_step\n    name = self.get_data(selector)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\api_test\\utils\\yamlutil.py\", line 39, in get_data\n    data = self.read_yaml(FilePath)\n  File \"C:\\Users\\Administrator\\PycharmProjects\\api_test\\utils\\yamlutil.py\", line 18, in read_yaml\n    with open(path, encoding='utf-8') as fp:\n"}, "parameters": [{"name": "selector", "value": "'get_case'"}], "start": 1680710535358, "stop": 1680710535376}], "start": 1680710535358, "stop": 1680710535376, "uuid": "f3a76d4f-c818-4843-b200-3a3d4ac5657f", "historyId": "1f946f06d0d459d9017402001e59e2e5", "testCaseId": "acaf052959b565644f9f58582f8b1e01", "fullName": "testcase.learn.test_learn.TestLearn#test_learn", "labels": [{"name": "story", "value": "测试用例"}, {"name": "parentSuite", "value": "testcase.learn"}, {"name": "suite", "value": "test_learn"}, {"name": "subSuite", "value": "TestLearn"}, {"name": "host", "value": "PC-202209231525"}, {"name": "thread", "value": "17280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.learn.test_learn"}]}