{"name": "xxxxx", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 2", "trace": "@allure.title(\"xxxxx\")\n    def test_xxx():\n>       assert 1==2\nE       assert 1 == 2\n\ntest\\test_aaa.py:6: AssertionError"}, "start": 1680710535112, "stop": 1680710535113, "uuid": "a288d3fc-4af3-45a7-b57b-19f45623cd4a", "historyId": "36b320f6c5c1c6d4c9fa49ffe04f7475", "testCaseId": "1d30475941eb63fa2693a2c9b0aa3ae3", "fullName": "test.test_aaa#test_xxx", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_aaa"}, {"name": "host", "value": "PC-202209231525"}, {"name": "thread", "value": "17280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_aaa"}]}